version: "3.8"

services:
  mongo:
    ## mongodb
    image: mongo
    container_name: restaurant-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - restaurant-data:/data/db

    ## mongo express
    ## backend server
    ## frontend server

volumes:
  restaurant-data:
